### ISSUE TITLE
"root" option doesn't work

### ISSUE THREAD

**Issue by BassOfBass** [Spence-S/simple-pug-loader#6]
Even if set it will throw this error:
```sh
ERROR in   Error: Child compilation failed:
  Module build failed (from ./node_modules/simple-pug-loader/index.js):
  Error: the "basedir" option is required to use includes and extends with "abso  lute" paths

```
I've tried other variations such as `basedir`/`baseDir` and none of them worked. Take note this option works fine in `pug-loader` with just `root`.
Here is [the reproduction](https://github.com/BassOfBass/test-repo).

**Comment by spence-s** [comment]
Thanks again @BassOfBass ! Do you want to try fixing this one? I _think_ you just need to add the option to the pugOptions object and it should work. We should also change the documentation there because we *are* using pugs file resolution for this loader and not webpacks in most cases. If not, no big deal I will be able to fix in a few days. Thanks again for the report!

**Comment by BassOfBass** [comment]
PUG and webpack loaders codebases are black magic for me, so I'll wait.

**Comment by spence-s** [comment]
fix published https://www.npmjs.com/package/simple-pug-loader
